/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-01 12:17:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>footer</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#total-footer{\n");
      out.write("	width: 420px;\n");
      out.write("    height:120;\n");
      out.write("    border-width: 2px;\n");
      out.write("    border-style:solid;\n");
      out.write("   \n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-div {\n");
      out.write("    background-color: silver;\n");
      out.write("    display: inline;\n");
      out.write("    display: flex;\n");
      out.write("    padding-left: 500px;\n");
      out.write("    \n");
      out.write("    \n");
      out.write("}\n");
      out.write(".footer li {\n");
      out.write("    list-style-type: none;\n");
      out.write("    height: 50px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <footer style=\"position: relative;margin-top:491px\">\n");
      out.write("        <div class=\"footer-div\">\n");
      out.write("            <div>\n");
      out.write("                <ul>\n");
      out.write("                    <h5>MEN</h5>\n");
      out.write("                    <li>Footwear</li>\n");
      out.write("                    <li>Clothing</li>\n");
      out.write("                    <li>Accessories</li>\n");
      out.write("                    <h5>WOMEN</h5>\n");
      out.write("                    <li>Footwear</li>\n");
      out.write("                    <li>Clothing</li>\n");
      out.write("                    <li>Accessories</li>\n");
      out.write("                    <h5>KIDS</h5>\n");
      out.write("                    <li>Footwear</li>\n");
      out.write("                    <li>Clothing</li>\n");
      out.write("                    <li>Accessories</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <ul>\n");
      out.write("                    <h5>FITNESS</h5>\n");
      out.write("                    <li>Running</li>\n");
      out.write("                    <li>Training</li>\n");
      out.write("                    <li>Classics</li>\n");
      out.write("                    <li>Walking</li>\n");
      out.write("                    <li>Mixed Martial Arts</li>\n");
      out.write("                    <li>Swimming</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <ul>\n");
      out.write("                    <h5>QUICK SHOP</h5>\n");
      out.write("                    <li>Running</li>\n");
      out.write("                    <li>Training</li>\n");
      out.write("                    <li>Classics</li>\n");
      out.write("                    <li>Walking</li>\n");
      out.write("                    <li>Mixed Martial Arts</li>\n");
      out.write("                    <li>Swimming</li>\n");
      out.write("                    <li>SALE</li>\n");
      out.write("                    <h5>NEW ARRIVALS</h5>\n");
      out.write("                    <li>New Arrivals</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <ul>\n");
      out.write("                    <h5>CUSTOMER SERVICE</h5>\n");
      out.write("                    <li>Contact Us</li>\n");
      out.write("                    <li>My Account</li>\n");
      out.write("                    <li>*Privacy Policy</li>\n");
      out.write("                    <li>*Terms And Conditions</li>\n");
      out.write("                     <li><a href=\"/SpringEcommerce/addProducts\">ADD PRODUCTS</a>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
