/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-01 12:17:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("   <title>Fashion Way</title>\n");
      out.write("    <style type=\"text/css\">\n");
      out.write("    header{\n");
      out.write("    background-color: rgb(129, 157, 187);\n");
      out.write("    color: white;\n");
      out.write("}\n");
      out.write(".logo{\n");
      out.write("    color: rgb(100, 2, 2);\n");
      out.write("    line-height: 10px;\n");
      out.write("    font-size: 25px;\n");
      out.write("    font-weight: 1000;\n");
      out.write("    font-style: italic;\n");
      out.write("    font-stretch: extra-expanded;\n");
      out.write("    text-shadow: #FFF 0px 0px 5px, #FFF 0px 0px 10px, #FFF 0px 0px 15px, #FF2D95 0px 0px 10px, #FF2D95 0px 0px 20px, #FF2D95 0px 0px 30px, #FF2D95 0px 0px 40px, #FF2D95 0px 0px 65px, -3px 3px 1px rgba(206,159,204,0);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logo-photo{\n");
      out.write("    border-radius: 50%;\n");
      out.write("    background-size: cover;\n");
      out.write("    width: 50px;\n");
      out.write("    height: 50px;\n");
      out.write("}\n");
      out.write(".header{\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: row;\n");
      out.write("    list-style-type: none;\n");
      out.write("    justify-content: space-evenly;\n");
      out.write("}\n");
      out.write(".header-two ul li{\n");
      out.write("    display: inline;\n");
      out.write("    margin-left: 25px;\n");
      out.write("   \n");
      out.write("}\n");
      out.write(".header-three ul li input{\n");
      out.write("    border-radius: 12px;\n");
      out.write("    border: 2px solid lightblue;\n");
      out.write("    height: 24px;\n");
      out.write("    width: 200px;\n");
      out.write("}\n");
      out.write(".header-two ul li button a{\n");
      out.write(" text-decoration: none;\n");
      out.write("}\n");
      out.write(".header-three{\n");
      out.write("  \n");
      out.write("   /* padding-left: 700px; */\n");
      out.write("}\n");
      out.write(".header-three ul li{\n");
      out.write("    display: inline;\n");
      out.write("    margin-left: 25px;\n");
      out.write("}\n");
      out.write(".header-three ul li button a{\n");
      out.write("    text-decoration: none ;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("button {\n");
      out.write("    padding: 0.6em;\n");
      out.write("    font-size: 12px;\n");
      out.write("    text-transform: uppercase;\n");
      out.write("    letter-spacing: 2.5px;\n");
      out.write("    font-weight: 500;\n");
      out.write("    color: #000;\n");
      out.write("    background-color: #fff;\n");
      out.write("    border: none;\n");
      out.write("    border-radius: 45px;\n");
      out.write("    box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);\n");
      out.write("    transition: all 0.3s ease 0s;\n");
      out.write("    cursor: pointer;\n");
      out.write("    outline: none;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   button:hover {\n");
      out.write("    background-color: #2EE59D;\n");
      out.write("    box-shadow: 0px 15px 20px rgba(46, 229, 157, 0.4);\n");
      out.write("    color: #fff;\n");
      out.write("    transform: translateY(-7px);\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   button:active {\n");
      out.write("    transform: translateY(-1px);\n");
      out.write("   }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("     <header>\n");
      out.write("    <div class=\"header\">\n");
      out.write("        <div class=\"logo\">\n");
      out.write("            <p>FASHION WAY</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"header-two\">\n");
      out.write("            <ul>\n");
      out.write("                <li><button id=\"men\"><a href=\"/SpringEcommerce/plp/men\">MEN</a></button></li>\n");
      out.write("                <li><button id=\"women\"><a href=\"/SpringEcommerce/plp/women\">WOMEN</a></button></li>\n");
      out.write("                <li><button id=\"kids\"><a href=\"/SpringEcommerce/plp/kids\">KIDS</a></button></li>\n");
      out.write("                <li><button id=\"beauty\"><a href=\"#show_message\">BEAUTY</a></button></li>\n");
      out.write("                \n");
      out.write("            </ul>\n");
      out.write("           </div>\n");
      out.write("          <div class=\"header-three\">\n");
      out.write("            <ul>\n");
      out.write("                    <li><input type=\"text\" ></li>\n");
      out.write("                    <li><button  class=\"forCart\"><a href=\"/SpringEcommerce/viewcart\">CART</a></button></li>\n");
      out.write("                     <li><button  class=\"forCart\"><a href=\"/SpringEcommerce/order\">ORDER</a></button></li>\n");
      out.write("                    <li><button class=\"forSignUp\"><a href=\"/SpringEcommerce/signup\">SIGNUP</a></button></li>\n");
      out.write("                    <li><button class=\"forLogin\"><a href=\"/SpringEcommerce/login\">LOGIN</a></button></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("    </div>\n");
      out.write("    </header><br><br>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
